version: '3.8'

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/data
    environment:
      CHROMA_SERVER_HOST: "0.0.0.0"
      CHROMA_SERVER_PORT: "8000"

volumes:
  chromadb_data: